# Generated by Django 3.1.3 on 2020-12-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Computer_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Computer',
            },
        ),
        migrations.CreateModel(
            name='Computer_Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CReserve_student', models.IntegerField()),
                ('CReserve_computer', models.IntegerField()),
                ('CReserve_date', models.DateField()),
                ('CReserve_start_time', models.TimeField()),
                ('CReserve_end_time', models.TimeField()),
            ],
            options={
                'db_table': 'Computer_Reserve',
            },
        ),
        migrations.CreateModel(
            name='Reservation_Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Queue_student', models.IntegerField()),
                ('Queue_datetime', models.DateField()),
            ],
            options={
                'db_table': 'Reservation_Queue',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_firstname', models.CharField(max_length=100)),
                ('Student_lastname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
