# Generated by Django 3.1.3 on 2020-12-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comstudreserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_reserve',
            name='CReserve_computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstudreserve.computer'),
        ),
        migrations.AlterField(
            model_name='computer_reserve',
            name='CReserve_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstudreserve.student'),
        ),
        migrations.AlterField(
            model_name='reservation_queue',
            name='Queue_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstudreserve.student'),
        ),
    ]
