# Generated by Django 3.1.2 on 2020-12-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_id', models.IntegerField()),
                ('Material_type', models.CharField(max_length=100)),
                ('Material_title', models.CharField(max_length=100)),
                ('Material_author', models.IntegerField()),
                ('Material_publication_date', models.DateField()),
                ('Material_shelf_rack', models.CharField(max_length=10)),
                ('Material_image', models.CharField(max_length=100)),
                ('Material_preface', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Material_Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrow_id', models.IntegerField()),
                ('Borrow_student', models.IntegerField()),
                ('Borrow_material', models.IntegerField()),
                ('Borrow_borrow_date', models.DateField()),
                ('Borrow_return_date', models.DateField()),
                ('Borrow_returned_date', models.DateField()),
            ],
        ),
    ]
