# Generated by Django 3.1.2 on 2020-12-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material_Borrow',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material_preface',
            new_name='preface',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material_publication_date',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material_shelf_rack',
            new_name='shelf_rack',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material_image',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Material_title',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='author',
            name='Author_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Material_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='Material_type',
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
    ]
