# Generated by Django 3.1.2 on 2020-12-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0002_auto_20201213_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
