# Generated by Django 3.1.3 on 2020-12-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth_reserve',
            name='BReserve_booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth'),
        ),
        migrations.AlterField(
            model_name='booth_reserve',
            name='BReserve_timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.timeslot'),
        ),
    ]
