# Generated by Django 3.1.3 on 2020-12-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comstudreserve', '0001_initial'),
        ('booth', '0002_auto_20201212_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth_reserve',
            name='BReserve_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstudreserve.student'),
        ),
    ]
