# Generated by Django 3.1.3 on 2020-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Administrator_username', models.CharField(max_length=100)),
                ('Administrator_firstname', models.CharField(max_length=100)),
                ('Administrator_lastname', models.CharField(max_length=100)),
                ('Administrator_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announcement_type', models.CharField(max_length=100)),
                ('Announcement_title', models.CharField(max_length=100)),
                ('Announcement_content', models.CharField(max_length=100)),
                ('Announcement_date', models.DateField()),
                ('Announcement_author', models.IntegerField()),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]
