# Generated by Django 3.1.3 on 2020-12-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Announcement_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.administrator'),
        ),
    ]
