# Generated by Django 3.1.3 on 2020-12-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_type', models.CharField(max_length=100)),
                ('Material_title', models.CharField(max_length=100)),
                ('Material_author', models.IntegerField()),
                ('Material_publication', models.DateField()),
                ('Material_shelf_rack', models.CharField(max_length=10)),
                ('Material_image', models.ImageField(upload_to='')),
                ('Material_preface', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
    ]
