# Generated by Django 3.1.3 on 2020-12-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comstudreserve', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Material_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.author'),
        ),
        migrations.CreateModel(
            name='Material_Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrow_borrow_date', models.DateField()),
                ('Borrow_return_date', models.DateField()),
                ('Borrow_returned_date', models.DateField()),
                ('Borrow_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('Borrow_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comstudreserve.student')),
            ],
            options={
                'db_table': 'Material_Borrow',
            },
        ),
    ]
