# Generated by Django 3.1.3 on 2020-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20201212_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='Material_author',
        ),
        migrations.AddField(
            model_name='material',
            name='Material_author',
            field=models.ManyToManyField(blank=True, to='material.Author'),
        ),
    ]
